[versions]
kotlinVersion = "1.4.31"
detektVersion = "1.15.0"
mokoResourcesVersion = "0.16.1"
androidVersion = "4.1.1"
appCompatVersion = "1.1.0"
tensorflowLiteVersion = "2.2.0"
mokoTensorflowVersion = "0.2.0"
mokoMediaVersion = "0.9.0"
coroutineWorkerVersion = "0.6.3"
constraintLayoutVersion = "1.1.3"
coreKtxVersion = "1.1.0"
playServicesVersion = "17.0.0"
androidDrawVersion = "v0.1"

[libraries]
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompatVersion" }
kotlinStdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinVersion" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayoutVersion" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
playServices = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesVersion" }
androidDraw = { module = "com.github.divyanshub024:AndroidDraw", version.ref = "androidDrawVersion" }
tensorflowLite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLiteVersion" }
mokoTensorflow = { module = "dev.icerock.moko:tensorflow", version.ref = "mokoTensorflowVersion" }
mokoResources = { module = "dev.icerock.moko:resources", version.ref = "mokoResourcesVersion" }
mokoMedia = { module = "dev.icerock.moko:media", version.ref = "mokoMediaVersion" }
coroutineWorker = { module = "com.autodesk:coroutineworker", version.ref = "coroutineWorkerVersion" }
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektVersion" }
